=== Cortan122/psybot/schemas/article.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "author": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "content": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "docx_url": {
      "format": "uri",
      "pattern": "^https://docs.google.com/document/d/",
      "type": "string"
    },
    "featured_image": {
      "type": "string"
    },
    "needs_subscription": {
      "type": "boolean"
    },
    "short_description": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "url": {
      "format": "uri",
      "type": "string"
    }
  },
  "required": [
    "author",
    "category",
    "content",
    "date",
    "docx_url",
    "title",
    "url"
  ],
  "type": "object"
}

=== Cortan122/psybot/data/techniques/Межличностные отношения/Непрерывное слушание.json
{
  "author": "Арина",
  "category": "Межличностные отношения",
  "content": "Простое, но мощное упражнение называется «Непрерывное слушание». Нам всем нужно чувствовать, что нас слышат,\nпонимают и заботятся о нас, и это упражнение может помочь и Вам, и Вашему партнеру ощутить это.\n\nУстановите таймер для этого упражнения (обычно достаточно трех-пяти минут) и дайте вашему партнеру выговориться.\nВы можете говорить о чем угодно, что на уме: о работе, школе, детях, друзьях или семье, стрессе.\n\nПока партнер говорит, ваша задача – делать одно и только одно: слушать. Не говорите вообще, пока не сработает\nтаймер. Просто слушайте своего партнера и впитывайте все это. Хотя Вы не можете говорить в течение этого\nвремени, Вы вольны оказывать своему партнеру невербальную поддержку или сочувствие с помощью языка тела, мимики\nили взглядов.\n\nКогда время закончится, поменяйтесь ролями и повторите упражнение.\n\n**Источник**: https://positivepsychology.com/couples-therapy-worksheets-activities/#exercises-couples-therapy",
  "date": "2023-02-15",
  "docx_url": "https://docs.google.com/document/d/1qeu1zegg4qf58vZ-rze0A6H5jnvgzFOG/edit#heading=h.30j0zll",
  "featured_image": "/images/Techniques/для пар прослушивание.png",
  "short_description": "Упражнение для пары:",
  "title": "Непрерывное слушание",
  "url": "/techniques/непрерывное-слушание/"
}

=== Cortan122/psybot/data/articles/Общие психологические знания/Депрессия.json
{
  "author": "Арина",
  "category": "Общие психологические знания",
  "content": "**Депрессия** – это распространенное и серьезное психическое расстройство, негативно влияющее на настроение, образ мыслей и поведение. К счастью, это заболевание излечимо. Депрессия вызывает чувство грусти и/или потерю интереса к занятиям, которые раньше приносили удовольствие. Она может привести к разнообразным эмоциональным и психическим проблемам, а также снизить способность к выполнению ваших функций на работе и дома.\n\n## Симптомы\n\nСимптомы депрессии могут варьироваться от незначительных до серьезных и могут включать в себя:\n* чувство грусти или подавленное настроение;\n* потерю интереса к занятиям, которые увлекали раньше или потерю удовольствия от этих занятий;\n* изменение аппетита – снижение или набор веса, не связанные с диетой;\n* бессонницу либо слишком долгий сон;\n* потерю энергии или повышенную утомляемость;\n* возрастание количества бессмысленных физических действий (например, неспособность усидеть на месте, хождение туда-сюда, движения руками), либо замедление движений и речи (эти симптомы должны быть достаточно выраженными, чтобы их заметили окружающие);\n* чувства никчемности и вины;\n* сложности в мышлении, концентрации и принятии решений;\n* мысли о смерти или суициде.\n\n## Постановка диагноза\n\nДля постановки диагноза депрессии симптомы должны длиться не меньше двух недель и быть отличными от вашего обычного предыдущего состояния.\nТакже некоторые заболевания могут вызвать похожие симптомы, поэтому важно исключить общие медицинские причины.\n\nСогласно оценкам, депрессией страдает каждый пятнадцатый взрослый человек (6.7%) в каждом конкретном году. Каждый шестой человек (16.6%) испытывает депрессию когда-либо в своей жизни. Депрессия может возникнуть в любом возрасте, но, чаще всего, впервые возникает в период от позднего подросткового возраста до середины третьего десятка. Женщины более подвержены депрессии, чем мужчины. Некоторые исследования показывают, что каждая третья женщина испытывает депрессию хотя бы раз в жизни. Фактор наследственности (родители, дети, родные братья и сестры) оказывает существенное влияние (примерно 40%) на вероятность возникновения депрессии.",
  "date": "2023-02-13",
  "docx_url": "https://docs.google.com/document/d/1uRRlOaXSI_WQpXhF394UcGnXsNwkEZ3E/edit",
  "featured_image": "/images/grief.jpg",
  "needs_subscription": false,
  "title": "Что такое депрессия?",
  "url": "/articles/депрессия/"
}

=== Cortan122/psybot/data/articles/Эмоции и чувства/Стокгольмский синдром.json
{
  "author": "Катя",
  "category": "Эмоции и чувства",
  "content": "«Стокгольмский синдром» или «синдром идентификации заложника» выглядит, как проявление симпатии со стороны жертвы по\nотношению к своему захватчику, агрессору, применяющему к ней насилие (*Annin, 1985*). В настоящее время тема стокгольмского\nсиндрома наиболее актуальна вследствие учащения актов насилия в общественных местах, в том числе в школах и университетах.\nО том, как можно проникнуться симпатией к нападающему, а также как обнаружить, что вы попались на этот крючок, расскажет\nнаша статья. Но сперва немного истории.\n\nПочему же этот феномен носит имя прекрасного шведского города – родины Карлсона? Всему виной – один пренеприятнейший\nинцидент, произошедший летом 1973 года. В тот день в Стокгольме одинокий бандит (позже к нему присоединился еще один)\nзахватил банк и взял четырех человек в заложники. Находясь в столь незавидном положении, под угрозой смерти, заложники\nтребовали от шведских властей, чтобы те выполнили все условия захватчиков. Сам по себе этот факт не слишком удивляет, не\nтак ли? Однако после освобождения заложников в результате грамотных действий шведской полиции, начали происходить странные\nвещи. Уже бывшие заложники заявили, что, находясь в плену, боялись именно полиции, а не своих пленителей, которым они\nпозже оплатили дорогостоящих юристов и в целом оказывали поддержку, выражали к ним сочувствие и сопереживание их дальнейшей\nсудьбе (*Serena, 2019*). Впоследствии один из похитителей был оправдан, после чего крепко сдружился с одной из бывших\nзаложниц. Другой же похититель, получивший серьезный срок, тем не менее сделался предметом обожания и получал множество\nписем от похищенных им прежде женщин.\n\nЧто же произошло? Почему люди, в отношении которых был совершен акт столь вопиющего насилия вдруг стали защитниками и\nобожателями своих бывших мучителей? Местный психиатр Нильс Бейерут, который в то время консультировал шведскую полицию\n(*Kamm, 1973*), придумал специальный термин, которым он объяснил поведение сотрудников банка – «Норрмальмсторгский синдром»\n(его-то потом и станут именовать «стокгольмским»). Строго говоря, именовать его «синдромом» не совсем верно, так как это\nскорее феномен, который психодинамическая традиция связывает с таким защитным механизмом психики, как «идентификация с\nагрессором». Оказавшись в ситуации насилия, человек зачастую испытывает огромный стресс и, не желая более пребывать в\nстоль опасном и страшном положении жертвы, начинает отождествлять себя с агрессором, перенимать некоторые его личностные\nчерты, копируя их и принимая за свои собственные. Вероятно, «стокгольмский синдром» является следствием из этого\nотождествления: заложник становится похожим на захватчика, после чего неминуемо чувствует схожесть и даже близость между\nним и собой. Отсюда иллюзорное понимание и сочувствие целям и мотивам агрессора, попытка оправдать и даже поспособствовать\nдействиям такого «родного», «понятного» и «близкого» человека.\n\nСам по себе «синдром» не опасен и не является ни в коей мере психическим заболеванием (*Grobar et al., 2018*). На самом\nделе, он даже способствует выживанию заложников, так как сочувствие потенциально действует в обе стороны – иногда мешая\nтеррористам хладнокровно убить захваченных. Опасность несут именно последствия подобного сопереживания: люди могут\nспособствовать целям захватчиков, укрывать их от полиции, в редких случаях даже жертвовать ради них собственной жизнью.\nВ каком-то смысле эти действия даже можно назвать оправданными, ведь жизнь заложника целиком зависит от его пленителя;\nпонимая, а скорее чувствуя это, захваченные в плен люди будут стремиться ублажить и пойти на поводу у тех, от чьего\nнастроения зависит, выживут они или незамедлительно погибнут. В то же время надежда, что агрессор смягчится, если\nбезоговорочно выполнять все его требования, заставляет людей безо всяких раздумий совершать самые разные действия в пользу\nзахватчиков, порой даже те, что напрямую противоречат здравому смыслу.\n\nХорошо, что по отчетам полиции, подобный феномен возникает всего лишь примерно в 8% случаев, то есть, является довольно\nредким явлением.\nИли нет? Дело в том, что «стокгольмский синдром» не исчерпывается только ситуациями реальных вооруженных захватов. Схожие\nпо принципу работы процессы могут возникать в целом ряде ситуаций и случаев, например, при семейном и сексуальном насилии\n(*Hill, 2019*), религиозных и национальных обрядах, лишении свободы, военных операциях, политических терактах и так далее.\nБолее того, нечто похожее нередко имеет место в авторитарных семьях или корпорациях. Иными словами – «стокгольмский\nсиндром» может подстерегать вас дома или на работе, вовсе не обязательно для этого сталкиваться с реальными вооруженными бандитами. В связи с этим необходимо понимать, какие факторы способствуют возникновению этого феномена, и научиться вовремя отдавать себе отчет, если с вами это произошло.\n\nСреди особенностей ситуации, способствующих возникновению «синдрома» можно выделить следующие:\n1. длительное нахождение в ситуации насилия;\n2. возможность установить эмоциональный контакт с агрессором;\n3. сильная зависимость от агрессора и наличие у агрессора более или менее «рациональных» причин для подобного поведения (им необязательно быть действительно рациональными, главное, чтобы жертве было легко поверить, что они являются таковыми, а насилие оправданным).\n\nИтак, если вы когда-нибудь почувствуете, что хотите исполнить все желания некоего человека, что понимаете его мотивы и\nиспытываете сочувствие, несмотря на то что из раза в раз он продолжает делать вам больно, спросите себя, а не попали ли\nвы в заложники, подобного сотрудникам одного далекого датского банка.\n\n## Литература\n1. Annin P., Hostages: Living in The Aftermath, 1985.\n2. Grobar M., Ethan Hawke, Noomi Rapace, Learn True Meaning Of 'Stockholm' Syndrome — Tribeca Studio, 2018\n3. Hill J., See What You Made Me Do: Power, Control and Domestic Abuse, 2019.\n4. Kamm H., Stockholm Police Seize 2 in Vault, Free 4 Hostages, 1973.\n5. Serena K., Stockholm Syndrome And The Strange Bank Robbery Behind It All That’s Interesting, 2018.",
  "date": "2023-01-12",
  "docx_url": "https://docs.google.com/document/d/1NPq0CjSz0bLVVxnWxhXb-gLZc2IZnOXi/edit",
  "featured_image": "/images/stokholm_syndrome.jpg",
  "needs_subscription": false,
  "title": "Стокгольмский синдром",
  "url": "/articles/стокгольмский-синдром/"
}

=== Cortan122/psybot/data/techniques/Самопознание/Жизненная история.json
{
  "author": "Арина",
  "category": "Самопознание",
  "content": "**Цель**: Помочь найти смысл и ценность в собственном опыте, исследуя свои сильные стороны.\n\nНаше восприятие себя сильно завязано на том, что мы о себе помним и как мы рассказываем о том, что помним. Часто\nлюди не замечают своих сильных сторон либо просто не используют их. Это может помешать в достижении поставленных\nцелей, в наполнении своей жизни смыслом.\n\nПри выполнении упражнения напишите историю своей жизни в трех частях: прошлое, настоящее и будущее. Вы можете\nпроявлять творческий подход, но важно подчеркнуть, что Ваша задача – сосредоточиться на своих сильных сторонах\nв каждом из трех разделов. Если есть возможность, Вы можете поделиться написанным со специалистом.\n\n**Инструкции/Подсказки для написания**:\n\n**Прошлое**: Напишите историю своего прошлого. Обязательно опишите трудности, которые Вы преодолели, и личные\nсильные стороны, которые позволили Вам это сделать.\n\n**Настоящее**: Опишите свою жизнь и то, кем Вы являетесь прямо сейчас. Чем Вы отличаетесь от своего прошлого «я»?\nКаковы Ваши сильные стороны сейчас? Как развивались Ваши сильные стороны? С какими проблемами Вы сталкиваетесь?\nКак Вы можете использовать свои сильные стороны для преодоления этих проблем?\n\n**Будущее**: Напишите о своем идеальном будущем. Как Ваша жизнь будет отличаться от нынешней? Как Вы можете\nиспользовать свои сильные стороны для достижения этого идеального будущего? Как будут расти Ваши сильные стороны?\nКаким человеком Вы надеетесь стать? Чем Вы будете отличаться от того, что есть сейчас? Чего бы Вы хотели достичь?\nНаконец, как Вы можете добиться этих целей?",
  "date": "2023-02-15",
  "docx_url": "https://docs.google.com/document/d/1ZKAuOb5_GRlO-dGNis50EDqWm3PDUBY-/edit",
  "featured_image": "/images/Techniques/жизненная история.png",
  "short_description": "основанная на сильных сторонах",
  "title": "Жизненная история",
  "url": "/techniques/жизненная-история/"
}

=== Cortan122/psybot/data/techniques/Межличностные отношения/Совместные действия.json
{
  "author": "Арина",
  "category": "Межличностные отношения",
  "content": "Выполняйте его в течение двух недель следующим образом:\n\n1. Выберите приятное занятие для совместного выполнения. Пример: вместе играйте в настольные игры, занимайтесь\nспортом, танцуйте, ходите в кино, ужинайте, занимайтесь чем-то творческим, вместе занимайтесь садоводством –\nчем-то, что нравится Вам обоим.\n\n2. Выберите занятие, которое Вы оба считаете важным или значимым. Пример: организация совместных счетов,\nвыполнение домашних обязанностей, решение сложных вопросов по взаимному удовлетворению, совместное решение\nпроблемы или вклад в улучшение окружающего мира.\n\n3. Позже запишите, что произошло в Вашей жизни во время и по завершении занятий. Как эти занятия повлияли на\nваше настроение? Обратите внимание, какие хорошие события произошли во время и после завершения мероприятий.\nЗапишите то, что произошло, в дневник.\n\n4. Обратите внимание на то, что благодаря Вашему выбору и действиям произошли эти хорошие, важные, осмысленные\nи доставляющие удовольствие действия и события.\n\n5. Выполняйте 2 новых приятных, значимых или важных занятия каждый день в течение двух недель, прежде чем\nпереключаться на другое.\n\n**Источник**: https://www.counselling-directory.org.uk/memberarticles/practice-happiness-psychology-exercises-for-couples-under-stress",
  "date": "2023-02-15",
  "docx_url": "https://docs.google.com/document/d/1oopWl9h_ovlVuVQSv7ux0-xxsa9iG5wP/edit#heading=h.gjdgxs",
  "featured_image": "/images/Techniques/пары совместные действия.png",
  "short_description": "Упражнение для пары: совместное выполнение приятных, важных и осмысленных действий",
  "title": "Совместные действия для пар",
  "url": "/techniques/совместные-действия/"
}

=== Cortan122/psybot/data/techniques/Самопознание/Квадрат баланса.json
{
  "author": "Ксюша",
  "category": "Самопознание",
  "content": "**Инструкция**:\n1. Начертите квадрат и разделите его на две части по вертикали.\n2. Слева вписывается сфера жизни (можно несколько), справа – напротив нее – отмечается ее уровень развитости в\nвашей жизни (например, можно поставить оценку от 1 до 10).\n3. Квадрат можно заполнять дважды в месяц, либо только подводить итог месяца, а затем сравнивать изменения.\n4. По каждой сфере затем следует прописать действия, которые помогут ее развить. Сферу «работа», например, могут\nразвивать размещение резюме, прохождение курсов, участие в форумах и пр.\n\n**Источник**: https://www.b17.ru/article/kpt_tehniki/",
  "date": "2023-02-15",
  "docx_url": "https://docs.google.com/document/d/1TTWnDXPBDCzXT6zKTychHabOO89j0fw7/edit#",
  "featured_image": "/images/Techniques/квадрат баланса.png",
  "short_description": "**Инструкция**: 1.",
  "title": "Квадрат баланса",
  "url": "/techniques/квадрат-баланса/"
}

=== Cortan122/psybot/data/articles/Межличностные отношения/Созависимость Карпман.json
{
  "author": "Катя",
  "category": "Межличностные отношения",
  "content": "Существует большое количество людей, чья жизнь подчинена поведению, пристрастиям, желаниям другого человека, и такая зависимость\nделает их несчастными. Созависимость в отношениях мешает полноценной жизни личности, ее самовыражению и самореализации, а также\nвыступает одним из ключевых факторов риска в процессе формирования тяжелых форм зависимости: токсикомании, алкоголизма, наркомании\n(*Соловьева, Шаповалова, 2020*).\n\nПсихологическая модель взаимодействия между людьми под названием «Треугольник Карпмана» была впервые описана американским\nпсихотерапевтом Стивеном Карпманом в 1968 году. Несмотря на то что изначально Карпман назвал эту схему «драматическим треугольником»,\nза ней закрепилось имя ее основателя. Что из себя представляет «треугольник Карпмана» и чем плоха такая модель взаимоотношений людей?\n\n**Треугольник Карпмана** – это одна из самых популярных моделей, описывающих созависимые деструктивные отношения. В ней участники\nпридерживаются одной из трех ролей: Жертвы, Преследователя или Спасателя (*Карпман, 2016*).\n\n1. **Роль Преследователя**. B этой роли человек много критикует, обвиняет других людей и приказывает им. Преследователь хочет\nдоминировать, потому что сам глубоко внутри уязвим и не уверен в себе. Он самоутверждается и отыгрывает собственные комплексы и\nстрахи за счет контроля над другими, не беря ответственность за происходящее.\n2. **Роль Спасателя**. В этой роли человек все время пытается помочь и дать совет (часто непрошенный). Так он надеется почувствовать\nсебя нужным и самоутвердиться за чужой счет. На самом деле ему невыгодно, чтобы жертва вышла из треугольника. Пока он спасает ее\nи вступает в схватку с Преследователем, он подпитывает свое чувство собственной значимости, повышает самооценку и может не решать\nсобственные проблемы.\n4. **Роль Жертвы**. Это самая важная роль в треугольнике Карпмана. Потому что каждый игрок в глубине души – Жертва. Человек в этой\nроли ведет себя так, будто он беспомощный, много жалуется и ищет, на кого бы сбросить ответственность. А еще Жертва жаждет внимания.\nЭта роль достаточно одобряема в глазах общества. Она может годами ничего не менять – ей просто нужен кто-то, кому она может\nпожаловаться (*Москаленко, 2000*).\n\n## Как работает треугольник\n\nПреследователь нападает на жертву. Жертва страдает и винит во всем других людей и обстоятельства. Спасатель защищает Жертву и\nпомогает ей убедиться в том, что она беспомощна и ничего не может. В этом конфликте никто не пытается решить проблему.\nНаоборот – все превращают проблему в трясину, которая засасывает еще сильнее.\n\nВ разных обстоятельствах мы можем играть разные роли. Например, в конфликте с партнером – Преследователя, в диалоге с боссом –\nЖертвы, в общении с другом – Спасателя. Каждая роль дает свою выгоду – мы это бессознательно считываем и вступаем в игру.\n\nВ основе созависимого поведения каждого участника лежит потребность в любви и в избавлении от мучительных и привычных переживаний,\nусвоенных в воспитавшей их системе созависимых отношений – чрезмерной тревоги, вины, одиночества, жалости к себе, обид,\nнеуверенности, раздражительности, гнева, отчаяния. Но использование ими любой роли из треугольника Карпмана усиливает эти измучившие\nих переживания и минимизирует возможность получения любви.\n\n## Как выйти из треугольника\n\nДраматический треугольник не встретить там, где люди обладают достаточно высоким уровнем осознанности, готовы к прямому диалогу\nи избегают манипуляций: как в свой адрес, так и в отношении других людей. При этом выход из «треугольника Карпмана» – длительный\nпроцесс.\n\nВажно проследить за собой и понять, какие роли вы выбираете.\n\n1. **Если вы играете в Жертву**, начните брать на себя больше ответственности. Отказывайтесь от непрошенных советов и примите тот факт,\n   что нравиться всем невозможно. В состоянии Жертвы много вторичных выгод. Человек их, как правило, не осознает, но на него они\n   влияют очень сильно. Одна из таких выгод – получить внимание, заботу и восхищение («Как ты только с этим справляешься?»).\n   Для Жертвы с такой вторичной выгодой страшный сон – лишиться внимания и участия других в ее жизни.\n3. **Если играете в Спасателя**, попробуйте деликатно спрашивать у других, нужна ли им помощь или совет. Если ничего не нужно,\n   позвольте человеку самому разобраться в ситуации.\n5. **Преследователям** важно научиться выражать мысли без критики и разговаривать с собеседниками спокойно и уважительно.\n\n## Итог\n\nИтак, можно выделить три роли, в которых люди вступают друг с другом в деструктивные взаимоотношения: Жертва, Спасатель и\nПреследователь. При этом в разных обстоятельствах люди могут играть разные роли. Эта модель взаимодействия не приносит счастья\nили удовлетворения ее участникам, поэтому важно отследить, преобладает ли в человеке какая-либо роль, и попробовать ее\nкорректировать.\n\n## Литература\n1. Карпман С., Жизнь, свободная от игр, 2016.\n2. Москаленко В. Д., Созависимость: характеристики и практика преодоления, 2000.\n3. Соловьева Е. А., Шаповалова В. Г., Теоретический анализ феномена созависимых отношений, 2020.",
  "date": "2023-01-11",
  "docx_url": "https://docs.google.com/document/d/1wZQ9zoAvwU-GzmxkdENwIvJlZQVheaKX/edit",
  "featured_image": "/images/codependency.jpg",
  "needs_subscription": false,
  "title": "Созависимость",
  "url": "/articles/созависимость-карпман/"
}

=== Cortan122/psybot/data/techniques/Работа с мыслями/Белая комната.json
{
  "author": "Ксюша",
  "category": "Работа с мыслями",
  "content": "**Время выполнения**: около 5 минут.\n\n**На что направлена техника**:\n- совладание с тревогой и другими неприятными для Вас эмоциями;\n- стабилизация эмоционального состояния;\n- рефлексия, развитие самосознания.\n\nВ ходе этого упражнения Вы будете наблюдать за работой своего сознания, представляя, что оно – белая комната, через которую проходят мысли. Выполнять упражнение можно в любом спокойном месте, сидя или лежа. Закройте глаза и сделайте несколько глубоких вдохов. Дышите медленно и ровно на протяжении всего упражнения.\n\n1. Представьте, что Вы находитесь в белой комнате среднего размера с двумя дверьми. (Вместо образа комнаты с\nдверьми можно взять более близкий Вам образ: например, фуникулер, на который пересаживаются мысли, или багажная\nлента в аэропорту и т.д.) Мысли входят в одну дверь и уходят через другую. Как только мысль появляется,\nконцентрируйтесь на ней и старайтесь отнести ее к категории оценочных или безоценочных. Пример оценочной мысли:\n«На завтрашнем выступлении я буду выглядеть глупо, надо мной будут смеяться»; пример безоценочной мысли: «Я\nиспытываю страх перед завтрашним выступлением, как же мне тревожно».\n2. Рассматривайте каждую мысль внимательно, с любопытством и состраданием до тех пор, пока она не уйдет. Не\nпытайтесь анализировать ее, только отмечайте, оценочная она или нет. Не оспаривайте ее, не старайтесь поверить\nили не поверить в нее. Просто осознавайте, что это – мысль, краткий миг Вашей мозговой активности, случайный\nгость Вашей белой комнаты.\n3. Остерегайтесь мыслей, которые Вы отнесли к категории оценочных. Они будут стараться завладеть Вами,\nзаставить Вас принять эту оценку. Смысл данного упражнения в том, чтобы отмечать, насколько «прилипчивы»\nоценочные мысли: как они застревают в Вашем сознании и как сложно от них избавиться. Вы определите, что мысль\nмучительна и оценочна по тому, как долго она остается в белой комнате, или по тому, что Вы начинаете испытывать\nкакие-либо эмоции в связи с ней.\n4. Старайтесь постоянно поддерживать ровное дыхание, сохранять ясный образ комнаты и дверей (или другого\nвыбранного Вами в начале упражнения места), следить за мыслями и классифицировать их. Помните, что мысль –\nэто просто мысль. Вы гораздо больше нее. Вы – тот, кто создает пространство, через которую мыслям позволено\nпроходить. У Вас их миллион, и они уходят, а Вы по-прежнему остаетесь. Мысль не требует от Вас никаких действий.\nМысль не обязует Вас верить в нее. Мысль – это не Вы.\n5. Просто наблюдайте, как мысли проходят через белую комнату. Позволяйте им проживать их недолгую жизнь и\nговорите себе, что они имеют право на существование, даже если они оценочные. Признавайте Ваши мысли, давайте\nим уйти, когда приходит время, и готовьтесь встречать новые – одну за одной.\n\nПродолжайте выполнять это упражнение до тех пор, пока не почувствуете, что Вы по-настоящему дистанцировались\nот своих мыслей. Делайте его, пока даже оценочные мысли не начнут проходить через комнату не задерживаясь.\n\n**Источник**: Маккей М., Скин М., Фаннинг П., «Когнитивно-поведенческая терапия для преодоления тревожности, страха, беспокойства и паники»",
  "date": "2023-02-12",
  "docx_url": "https://docs.google.com/document/d/1i2MZ6xT61o-nNKWLGj_rGm1LaqeldoPU/edit#heading=h.gjdgxs",
  "featured_image": "/images/Techniques/белая комната.png",
  "needs_subscription": true,
  "short_description": "Техника «»",
  "title": "Белая комната",
  "url": "/techniques/белая-комната/"
}
