=== Cortan122/psybot/schemas/article.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "properties": {
    "author": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "content": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "docx_url": {
      "format": "uri",
      "pattern": "^https://docs.google.com/document/d/",
      "type": "string"
    },
    "featured_image": {
      "type": "string"
    },
    "needs_subscription": {
      "type": "boolean"
    },
    "short_description": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "url": {
      "format": "uri",
      "type": "string"
    }
  },
  "required": [
    "author",
    "category",
    "content",
    "date",
    "docx_url",
    "title",
    "url"
  ],
  "type": "object"
}

=== Cortan122/psybot/data/articles/Психология и практика/Как улучшить концентрацию и внимательность.json
{
  "author": "Арина",
  "category": "Психология и практика",
  "content": "У всех нас были ситуации, когда мы несмотря на горящий дедлайн и\nважность задачи никак не могли сконцентрироваться. В цифровую эпоху\nконцентрироваться на чем-то одном особенно сложно, ведь нескончаемый\nпоток информации, уведомлений и сообщений старается завладеть нашим\nвниманием.\n\nНеспособность сосредоточиться на текущей задаче - одна из болезней\nнашего времени. Именно поэтому проблема улучшения способности\nфокусироваться так актуальна.\n\n## Факторы, влияющие на концентрацию\n\n**Гаджеты.** В процессе выполнения какой-либо задачи на нас обрушивается\nогромное количество информации из компьютера, телефона или телевизора.\nИсследователи обнаружили, что наш мозг настолько настроен на это\nотвлечение, что просто вид нашего смартфона ухудшает нашу способность\nконцентрироваться.\n\n**Недостаточный сон**. Ученые обнаружили, что недостаток сна может\nпривести к замедлению мыслительных процессов и снижению концентрации\nвнимания. В результате недостаточного сна ваша способности выполнять\nзадачи, особенно связанные с мышлением или логикой, могут серьезно\nпострадать.\n\n**Недостаточная физическая активность**. Вы когда-нибудь замечали, как\nэнергичные физические упражнения заставляют вас чувствовать себя более\nрасслабленным и энергичным в течение всего дня? Когда вы не занимаетесь\nфизической активностью, ваши мышцы могут стать напряженными. Вы можете\nпочувствовать стеснение в шее, плечах и груди, и такой постоянный\nдискомфорт может повлиять на вашу концентрацию.\n\n**Пищевые привычки**. То, что мы едим, влияет на наше самочувствие, в\nтом числе и на ясность ума в течение дня. Если мы не насыщаем наш мозг\nнеобходимыми питательными веществами, мы начинаем испытывать такие\nсимптомы, как потеря памяти, усталость и отсутствие концентрации. Диета\nс низким содержанием жиров может нарушить концентрацию внимания, потому\nчто мозг нуждается в определенных незаменимых жирных кислотах.\n\nОграничительные диеты могут негативно повлиять на концентрацию внимания,\nне обеспечивая мозг необходимыми питательными веществами или вызывая\nчувство голода, тяжесть или плохое самочувствие в организме, которые\nотвлекают сами по себе.\n\n**Окружающая среда.** В зависимости от того, что вы делаете, окружающая\nсреда может повлиять на ваше внимание. Очевидно, что слишком громкий\nуровень шума является проблемой, но многие люди также испытывают\nтрудности с концентрацией внимания, когда слишком тихо. Важен не только\nобщий уровень шума, но и тип шума: расслабляющая музыка или звуки дрели.\nКомфортный уровень освещенности и влажности, а также оптимальная\nтемпература положительно сказываются на концентрации.\n\n**Эмоциональное состояние**. Негативные эмоции, стресс негативно\nсказываются на концентрации. Интенсивное позитивное переживание так же\nможет затруднять процесс работы.\n\n**Здоровье**. Такие заболевания, как диабет, гормональный дисбаланс и\nнизкое количество эритроцитов, могут повлиять на нашу концентрацию.\nНекоторые лекарства также вызывают у вас сонливость или головокружение и\nсерьезно ухудшают внимание.\n\n**Вредные привычки.** Образ жизни, который включает в себя чрезмерное\nупотребление алкоголя, курение может бросить вызов нашей памяти и\nспособности концентрироваться и сосредотачиваться.\n\nЕсли вы считаете, что ваши способности к концентрации выходят за рамки\nнормы проконсультируйтесь со специалистом.\n\n## Что может помочь вам лучше сосредоточиться?\n\nУстраните отвлекающие факторы.\n\nВозьмите за правило выделять время в своем расписании для выполнения\nопределенной задачи. Попросите, чтобы вас не отвлекали ваши близкие или\nколлеги. Или изначально выберете место, где другие вряд ли потревожат\nвас: библиотеку, коворкинг, отдельную комнату.\n\nЗакройте социальные сети и другие приложения, отключите уведомления и\nдержите телефон в сумке или рюкзаке. Исследователи обнаружили, что\nкогнитивные способности были значительно улучшены, когда телефон был вне\nполя зрения, а не просто выключен.\n\nИсключите многозадачность. Попытка выполнять несколько действий\nодновременно заставляет дает иллюзию продуктивности. Но, увы, это\nприводит лишь к обратному эффекту - снижению производительности. При\nэтом многозадачность часто приводит к эмоциональному выгоранию. Примеры\nмногозадачности включают в себя прослушивание подкаста во время ответа\nна электронное письмо или разговор с кем-то по телефону во время\nнаписания отчета. Такая многозадачность не только мешает вам\nсосредоточиться, но и ставит под угрозу качество вашей работы.\n\nПрактикуйте внимательность и медитацию. Медитация или практика\nосознанности могут улучшить самочувствие и психическое здоровье, а также\nулучшить концентрацию. Во время медитации наш мозг становится более\nспокойным, а наше тело расслабляется. Попробуйте пару минут посидеть с\nзакрытыми глазами и сконцентрировать свое внимание на дыхании. По началу\nвам в голову будут приходить различные мысли, замечайте их и\nпостарайтесь отпускать. Сфокусируйтесь на ощущениях в теле,\nпоследовательно расслабляйте мышцы. Регулярно практикуя медитации, вы с\nбольшой вероятностью станете более продуктивным.\n\n## Литература\n\n1. McDiarmid C. Concentration //Probabilistic methods for algorithmic discrete mathematics. – Springer, Berlin, Heidelberg, 1998. – С. 195-248.\n2. Csikszentmihalyi M., Csikzentmihaly M. Flow: The psychology of optimal experience. – New York : Harper & Row, 1990. – Т. 1990.\n3. Styles E. The psychology of attention. – Psychology Press, 2006\n4. Compton R. J. The interface between emotion and attention: A review of evidence from psychology and neuroscience //Behavioral and cognitive neuroscience reviews. – 2003. – Т. 2. – №. 2. – С. 115-129..",
  "date": "2022-10-30",
  "docx_url": "https://docs.google.com/document/d/1EK6JL9ot1dNLtj34VkcPqRg6Irka2AuN",
  "title": "Как улучшить концентрацию и внимательность",
  "url": "/articles/как-улучшить-концентрацию-и-внимательность/"
}

=== Cortan122/psybot/data/techniques/Работа с эмоциями/Злость и гнев.json
{
  "author": "Катя",
  "category": "Работа с эмоциями",
  "content": "Как и другие чувства, чувства злости и гнева являются нормальными человеческими переживаниями, требующими\nсвоего признания и выражения. В то же время выражение этих чувств не должно приводить к причинению ущерба\nсебе и другим. Переживание чувств злости и гнева может побуждать человека к изменению сложившейся системы\nотношений, являться стимулом к более решительным действиям. Часто эти чувства появляются в тех случаях,\nкогда человек чувствует себя недооцененным, обделенным, игнорируемым, отвергнутым, непонятым, а также когда\nвозникает угроза его интересам. Эти чувства также нередко возникают в ответ на агрессию извне, при\nпереживании боли и психической травмы. Злость, гнев и ярость, как правило, входят в структуру переживаний,\nхарактерных для посттравматических состояний.\n\nЛичность может по-разному относиться к подобным чувствам: одни позволяют себе их открыто выражать, другие\nсклонны эти чувства подавлять. Нередко открытому выражению злости и гнева мешает страх потери над ними\nконтроля, причинения ущерба окружающим, либо представления о моральной недопустимости этих переживаний.\nПризнание естественности и даже необходимости этих чувств способствует обретению способности ими управлять и\nнаходить оптимальные способы их выражения.\n\nДанное упражнение позволяет выразить эти чувства в метафорической, изобразительной форме и может\nслужить основой для развития навыков управления своим гневом.\n\n**Рекомендуемое время на выполнение упражнения**: 45-60 минут.\n\n**Материалы**: белая бумага размером А3; старые газеты и журналы с иллюстрациями; клей, ножницы.\n\n## Инструкция по выполнению упражнения\n\n### Подготовка\nПостарайтесь вспомнить различные проявления чувств злости и гнева на эмоциональном и физическом уровне,\nвозможно, внутренне обращаясь к какому-то событию из Вашей жизни.\n\n### Основная часть\n1. Просмотрите иллюстрации в газетах и журналах и подберите несколько картинок, которые бы отвечали на\nвопрос «На что похожи мои чувства злости и гнева?». При выполнении данного упражнения лучше пользоваться\nизображениями неодушевленных предметов (природные и неприродные объекты).\n2. Вырежьте эти картинки.\n3. Посмотрите на вырезанные картинки, передающие Ваши чувства злости и гнева, и постарайтесь описать\nследующие характеристики, связанные с изображенными объектами или их группами:\n   - масса, размер, текстура и температура;\n   - ощущения, которые возникали бы у Вас, если бы Вы взяли один или несколько объектов в свои руки;\n   - какие звуки способны произвести данные предметы;\n   - какие звуки вы хотели бы произвести с помощью данных предметов (предмета);\n   - что мог бы сказать этот предмет (предметы);\n   - где этот предмет (предметы) находятся;\n   - являются ли эти предметы неподвижными или они движутся;\n   - если они движутся, то как, в каком ритме и с какой скоростью.\n4. Вновь посмотрите иллюстрации в газетах и журналах и подберите один или несколько рисунков, которые могли\nбы служить «помощниками» предметам, изображенным на предыдущих картинках.\n5. Перемещая первые и вторые рисунки на листе бумаги, постарайтесь найти для них оптимальное расположение\nотносительно друг друга и затем приклейте их.\n6. Дождитесь, чтобы чувства злости и гнева, проявившиеся в процессе работы, стабилизировались, и чтобы Вы\nпочувствовали себя достаточно спокойно.\n\n### Описание и самоанализ\n1. Опишите, что произвело на Вас наиболее сильное впечатление в этом упражнении.\n2. Поясните, что общее между чувствами злости и гнева и найденными Вами рисунками.\n3. Опишите качества выбранных вами предметов-«помощников». Как они «помогают» предметам, ассоциирующимся со\nзлостью и гневом?\n4. Поясните, почему Вы расположили те и другие картинки именно таким образом?\n5. Что предметы-«помощники» могут символизировать в Вашей жизни, как это может помочь Вам лучше выражать\nчувства злости и гнева?\n6. Подумайте, какие еще способы конструктивного выражения этих чувств возможны.\n7. Подумайте, чем выражение чувств злости и гнева может быть для Вас полезно, к каким изменениям в Вашей\nжизни это могло бы привести.\n\n**Примечание**: Вы можете использовать данное упражнение для работы с другими чувствами – как положительными,\nтак и отрицательными.\n\n**Источник**: https://psy.wikireading.ru/21606",
  "date": "2023-02-12",
  "docx_url": "https://docs.google.com/document/d/1Nr0Xyx0WzAD72xoLUoEsvwQCsI3dE93-/edit#",
  "featured_image": "/images/Techniques/злость и гнев.png",
  "needs_subscription": true,
  "short_description": "Техника работы со злостью и гневом",
  "title": "Злость и гнев",
  "url": "/techniques/злость-и-гнев/"
}

=== Cortan122/psybot/data/articles/Межличностные отношения/Абьюзивные отношения.json
{
  "author": "Катя и Арина",
  "category": "Межличностные отношения",
  "content": "«Раз все так плохо, почему просто не уйти?» – очень распространенная реакция на рассказы об абьюзивных отношениях.\nАбьюз – термин, который пришел к нам из английского языка, в русском этот термин ближе всего к слову «насилие». Абьюз помимо физического бывает эмоциональным, экономическим, сексуальным и репродуктивным. Несмотря на кажущуюся сложность и непохожесть абьюзивных отношений, цикл абьюза везде одинаковый.\n\n## Цикл абьюза\n1. **«Ничего не предвещало беды»**. В начале отношений большая часть абьюзеров стараются казаться идеальными партнерами, они дарят подарки, дают почувствовать жертве свое обожание. Внимание и любовь рассеивают ее бдительность. Глаз замыливается и все «красные флажки» проходят мимо. Отношения завязываются очень быстро, чтобы жертва не успела одуматься и чтобы она отдавала контроль над собой.\n2. **Маска спадает**. Спустя время абьюзер начинает понемногу проявлять свою истинную сущность. Происходит активная проверка и нарушение личных границ. «Не одевайся так откровенно». «Эти друзья плохо на тебя влияют, не общайся с ними». При попытках сопротивления абьюзер использует манипуляции, газлайтинг (отрицание случившегося). Он постарается повернуть ситуацию так, чтобы жертва еще осталась виноватой.\n\n    Жертва в этот период проходит через несколько стадий. Она:\n    * **Терпит** в надежде, что скоро все будет как в начале отношений, а это лишь период.\n    * **Старается забыть** о все нарастающих проблемах и делает вид, что ничего не происходит\n    * **Старается изменить** абьюзера, ожидая что она может на него повлиять.\n    * **Меняет себя**. Жертва пытается подстроиться под непредсказуемое поведение абьюзера, следуя идее партнера о том, что проблема в ней(жертве).\n\n3. **Акт насилия**. Пиковая точка, после которой жертва может осознать ситуацию и попытаться уйти из отношений.\n4. **Вернуть любой ценой**. Абьюзер может начать извиняться, убеждать что жертва все не так поняла, попытаться все превратить в шутку или ошибку.\n5. **«Медовый месяц»**. Партнер становится «нормальным», может даже согласиться сходить к психологу, жертва же может передохнуть, увы, ненадолго.\nДалее круг замыкается, становится короче (без первого пункта), и быстрее.\n\n## Признаки абьюзивных отношений\n* **Подрывание самооценки и упреки**. Неуместные комментарии, обидные прозвища под соусом «я же любя». Со временем жертва может привыкнуть и начать думать о себе в негативном ключе, что облегчает контроль. «Кому ты кроме меня такой нужен?»\n* **Контроль**. Отслеживание передвижений, проверка социальных сетей, лишение финансов, приказной тон, отношение как к ребенку. Все конечно же оправдывается заботой.\n* **Вина**. Любимый инструмент абьюзеров. От жертвы будут требоваться постоянные оправдания даже за безобидные вещи, например, улыбка официантке.\n«Я столько для тебя сделала, а ты..»\n* **Обесценивание**. Увлечения жертвы глупы, проблемы надуманы, чувства преувеличены.\n\n## Проблема выхода из абьюзивных отношений\nК сожалению, причин, по которым выйти из абьюзивных отношений сложно, много, а их устранение часто почти невозможно без сторонней помощи. Разберем некоторые из причин.\n* **А по-другому и не бывает**. Часто происходит так, что жертва привыкла к абьюзивному сценарию отношений, усвоив его из романтической жизни своих родителей и окружения. Так же, нельзя сбрасывать со счетов культуру. Видели ли вы хоть одну мелодраму о здоровых отношениях? Вряд ли, ведь «все счастливые семьи похожи друг на друга, каждая несчастливая семья несчастлива по-своему». У жертв даже нет представления о том, как можно взаимодействовать с партнером, не смиряясь с манипуляциями и насилием.\n* **Ты этого достойна**. Из-за низкой самооценки жертва может считать, что лучше уже никогда не будет и «кому я такая вообще буду нужна».\n* **Эмоциональные качели**. Непредсказуемое чередование «кнута» и «пряника» делает жертву буквально зависимой от отношений. Нормальные взаимоотношения вызывают ломку от остроты ощущений.\n\n## Что делать?\n\n1. Возвращать круг общения. Друзья, родственники, группы поддержки. Вам нужна опора, не бойтесь просить о помощи.\n2. Действовать стоит без ведома абьюзера: создать финансовую подушку (продать что-нибудь, занять), найти место куда можно переехать, обратиться в [специализированные центры](https://nasiliu.net/karta-pomoshhi/)\n3. Оборвать **все** контакты с абьюзером и не реагируйте на его провокации, если он все же с вами свяжется.\n4. Заняться собой. Уделять время своему психологическому и физическому здоровью. Общаться с близкими людьми, заняться своими любимыми хобби.\n\nПомните, что вы заслуживаете любви и здоровых отношений.\n\nТест: [Есть ли в ваших отношениях психологическое насилие?](https://nasiliu.net/quiz/est-li-v-vashih-otnosheniyah-psihologicheskoe-nasilie2/)\\\nВидео: [Личный опыт домашнего насилия](https://youtu.be/CeeTtYLxsw4)\n\n## Что почитать об абьюзивных отношениях:\n-   Таня Танк [«Бойся, я с тобой»](https://www.litres.ru/tanya-tank/boysya-ya-s-toboy/)\n-   Ланди Бэнкрофт [«Почему он делает это? Кто такой абьюзер и как ему противостоять»](https://www.litres.ru/landi-benkroft/pochemu-on-delaet-eto-kto-takoy-abuzer-i-kak-emu-protivosto/chitat-onlayn/)\n-   Джексон Маккензи [«Psychopath Free. Как распознать лжеца и манипулятора среди партнеров, коллег, начальников и не стать жертвой обмана»](https://www.litres.ru/dzhekson-makkenzi/psychopath-free-kak-raspoznat-lzheca-i-manipulyatora-sredi-partnerov-kolleg-nachalnikov-i-ne-stat-zhertvoy-obmana/)\n-   Анна Пашкова [«Токсично. Как построить здоровые отношения и не вляпаться»](https://eksmo.ru/ebook/toksichno-kak-postroit-zdorovye-otnosheniya-i-ne-vlyapatsya-ITD957732/)\n-   [Ненасильственное общение, Маршалл Розенберг](https://www.ozon.ru/category/nenasilstvennoe-obschenie-marshall/)\n\n## Фильмы об абьюзивных отношениях:\n1. **Изчезнувшая** – при просмотре фильма сложно однозначно сказать, кто является абьюзером. Сюжет о загадочном исчезновении супруги смотрится бодро, а разрушение многих стереотипов о гендерных ролях греет душу.\n2. **Мама** – фильм является психологическим триллером, поэтому будьте готовы к непростым эмоциям. Однако присмотревшись поближе к действиям героев можно заметить всевозможные виды психологического давления и манипуляций.\n3. **Большие глаза**. Тут уже не просто абьюз, но и трудовая эксплуатация в мире художественного искусства цветущей Америки 50-х годов. Кристоф Вальц, как всегда, умопомрачителен в роли подлеца.",
  "date": "2022-10-30",
  "docx_url": "https://docs.google.com/document/d/1_so4XE6XVGVrl_iTFB0G9Lx_XJmvaL6O",
  "featured_image": "/images/abusive_relationships_1.jpg",
  "title": "Абьюзивные отношения",
  "url": "/articles/абьюзивные-отношения/"
}

=== Cortan122/psybot/data/articles/Эмоции и чувства/Чувство вины.json
{
  "author": "Катя",
  "category": "Эмоции и чувства",
  "content": "Вина – чувство не очень приятное, но полезное для социализации. Переживая неловкость за плохой и вредный для других поступок,\nмы замечаем, когда и какие наши действия причиняют людям боль, узнаем об их границах и потребностях, развиваем в себе чуткость\nи внимательность. Поэтому механизм вины отчасти регулирует человеческие отношения и сигнализирует нам, когда мы действуем\nвразрез со своими ценностями.\n\nПроживая вину адекватно, мы готовы действовать, и в этом ее созидательная для психики функция. Человеку не нравится, что он\nсделал, и он хочет скорее исправить последствия поступка, компенсировать причиненный другому ущерб. Все это – пример того,\nкак конструктивно пережить вину (*Miceli, Castelfranchi, 2018*).\n\nЕсть и другая вина – деструктивная (или невротическая). Она бесполезна и разрушительна. Можно годами ощущать себя виноватым\nбез причины. Психоаналитик Карен Хорни описывает случаи, когда человек считает, что не заслуживает ничего, кроме страданий,\nили фоново ожидает упреков и недовольства от любого, кто вступает с ним в контакт. В споре он слепо принимает сторону оппонента,\nа если собеседник исчез из поля зрения – например, не отвечал на сообщения какое-то время – такой человек моментально обвинит в\nэтом себя (*Хорни, 1993*).\n\nКонструктивная форма вины связана с конкретными ситуациями и поэтому осознается. Деструктивная вина, наоборот, как правило,\nне осознается и присутствует в жизни человека как фон.\n\nЗдесь мы разберемся, как устроена вина, какой она бывает и чем она отличается от стыда.\n\n## Чем чувство стыда отличается от чувства вины\n\nСуть различий между ними в том, что чувство вины направлено как бы вовне, а стыд направлен внутрь.\n\nВина возникает в момент выбора. Когда мы выбирает один объект, мы чувствуем вину перед другим. Стыд же всегда затрагивает\nотношения с самим собой. И хотя мы говорим, что нам стыдно перед друзьями или коллегами, взгляд других людей – это зеркало,\nв котором отражается наше представление о себе. Стыд возникает, когда наше истинное «Я» сталкивается с идеальным образом самого\nсебя и не выдерживает несоответствия.\n\nСтыд может быть сформирован значимыми фигурами в прошлом. Например, родители одергивали эмоционального ребенка, потому что\nбыть шумным, громким, эмоциональным – стыдно. Ребенок воспринимал многочисленные «нельзя» как осуждение и отвержение.\nВпоследствии человек продолжает жить, ориентируясь на окружающих и воспринимая себя неуместным и жалким.\n\n## Вина, стыд и ответственность\n\nНормальное чувство вины – это опыт ответственности. Человек переживает, что в результате его действий кому-то в мире стало\nплохо. Возможно, этот поступок был для него важным, но близкому причинил боль или обернулся нежелательными последствиями.\nТак как прошлое изменить нельзя, остается исправить настоящее и будущее (*Julle-Daniere et al., 2020*).\n\nЧувство вины основывается на негативной оценке моральности своих действий, поступков, убеждений. Конструктивная вина связана с\nпринятием ответственности за свои поступки, которые принесли вред другим людям. Осознание ответственности за реальную вину –\nэто важный момент. В таком случае человек не станет оправдываться за содеянное, а скорее объяснит, какие обстоятельства\nпобудили его поступить таким образом. Например, он скажет: «Знаю, что подвел тебя, не одолжив денег, но у меня были на них свои\nпланы» (*Niehues, 2010*).\n\nСтыд, наоборот, не связан с вопросами ответственности. Он связан с воспринимаемым несоответствием между реальным и идеальным «Я»,\nкогда человек считает, что он не похож на идеальный образ себя. Например, он может стыдиться своих недостатков, может также\nиспытывать стыд (а не чувство вины) за совершенную им ошибку.\n\n## Деструктивная вина\n\nДеструктивная вина заставляет чувствовать себя ничтожным, камнем преткновения, когда поводов для этого нет. Человек берет\nна себя ответственность за то, к чему не причастен.\n\nНапример, в романтической паре один человек имеет замкнутый характер: время от времени «уходит в себя». А второй чувствует\nстрах, тревогу или возмущение. Он считает себя причиной меланхоличного настроения партнера и требует от того или подтверждения,\nили опровержения, что приводит к неконструктивному конфликту (*Хорни, 1993*).\n\n## Из-за чего может возникнуть деструктивная вина\n\nЕсли мама злилась, тревожилась и не объясняла, что происходит, ребенок делал вывод, что маме с ним плохо. И верил, что может\nвсе исправить. Ребенок приписывал себе авторство над родительским настроением и привык угадывать эмоции тех, кто рядом.\nДругой пример – враждебная атмосфера, где ребенка игнорируют. Злость нельзя направить на взрослых: это может быть опасно.\n\n## Что с этим делать\n\nСперва нужно найти источник вины, переосмыслить опыт и увидеть его с другой стороны. Ведь правда в том, что автором настроения\nмамы была она сама, но не знала, как с этими чувствами обойтись и как их доступно объяснить ребенку. Важно мысленно вернуть\nответственность другим людям за их состояние.\n\nЗатем нужно отреагировать, то есть, прожить и выразить чувства, которые возникали в прошлых ситуациях: например, выразить\nстрах потерять мамину любовь или злость за то, что она не удовлетворяла ваши потребности.\n\nВажно отыскать в себе собственные ориентиры и ценности и начать им следовать.\n\n## Итог\n\nИтак, нормальное чувство вины – это опыт ответственности. Вина может быть полезной в рамках общества. Однако есть и\nдеструктивная вина, которая может преследовать человека долгие годы. Она заставляет человека чувствовать себя ничтожным.\nСтоит отличать вину от стыда: вина направлена наружу, стыд направлен внутрь. Важно выражать, проговаривать, признавать эти\nчувства для того, чтобы в них не застревать.\n\n## Литература\n\n1. Хорни К., Невротическая личность нашего времени, 1993.\n2. Julle-Danière E., Whitehouse J., Vrij A., Gustafsson E., Waller B. M., The social function of the feeling and expression of guilt, 2020.\n3. Miceli M., Castelfranchi C., Reconsidering the differences between shame and guilt, 2018.\n4. Niehues J., The social and sociological significance of ‘guilt’: Exemplification of “guilt” in the historical context of post-war Germany, 2010.",
  "date": "2023-01-11",
  "docx_url": "https://docs.google.com/document/d/1zKen0cZj_mf0w98z45bCOHbNiWokzeT2/edit#",
  "featured_image": "/images/fault.jpg",
  "needs_subscription": true,
  "title": "Чувство вины",
  "url": "/articles/чувство-вины/"
}
