=== Cortan122/psybot/schemas/recommendation.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "items": {
    "additionalProperties": false,
    "properties": {
      "author": {
        "type": [
          "string",
          "null"
        ]
      },
      "content": {
        "type": "string"
      },
      "country": {
        "type": "string"
      },
      "duration": {
        "type": "string"
      },
      "episodes": {
        "type": "integer"
      },
      "extra_content": {
        "type": "string"
      },
      "genre": {
        "type": "string"
      },
      "image_urls": {
        "items": {
          "type": "string"
        },
        "type": "array"
      },
      "needs_subscription": {
        "type": "boolean"
      },
      "title": {
        "type": "string"
      },
      "year": {
        "type": "integer"
      }
    },
    "required": [
      "author",
      "content",
      "image_urls",
      "needs_subscription",
      "title"
    ],
    "type": "object"
  },
  "type": "array"
}

=== Cortan122/psybot/data/recommendations/Books.json
[
  {
    "author": "Ксюша",
    "content": "Книга состоит из 85 глав-рекомендаций. Каждая глава посвящена одному из правил, принципов, описанию инструментов психологического консультирования.\n\n\"Дар психотерапии\" позволяет взглянуть на профессию психотерапевта изнутри благодаря множеству описанных в ней случаев из практики автора.",
    "image_urls": [],
    "needs_subscription": true,
    "title": "Дар психотерапии Ялом"
  },
  {
    "author": "Ксюша",
    "content": "Книга побуждает задуматься о таких экзистенциальных вопросах как смысл жизни, смерть, старение.",
    "image_urls": [],
    "needs_subscription": false,
    "title": "Все мы творения на день Ялом"
  },
  {
    "author": "Саша",
    "content": "Книга - “успокоительное”. Если в жизни все плохо, видится мрачное будущее и кажется, что ориентиры потеряны, а целей и смысла нет, то эта книга - для вас. Здесь не будет ужасных подробностей про концлагерь, в ней рассказывается, как выжить в самой трудной ситуации.",
    "image_urls": [
      "/images/Books/сказать жизни да.jpeg"
    ],
    "needs_subscription": false,
    "title": "Виктор Франкл «Сказать жизни «Да!»: психолог в концлагере»"
  },
  {
    "author": "Саша",
    "content": "Книга помогает пересмотреть отношение к стрессу: воспринимать его не как что-то плохое, а как механизм адаптации к тяжелым условиям, как мощный источник энергии и универсальный способ закалки характера. Книга научит как из стресса извлекать пользу",
    "image_urls": [],
    "needs_subscription": true,
    "title": "Келли Макгонигал «Хороший стресс как способ стать сильнее и лучше»."
  },
  {
    "author": "Саша",
    "content": "Одна из основополагающих книг по психологии человеческих взаимоотношений. Эрик Берн описывает различные “игры” людей - жизненные сценарии, определяющие поведение человека, способы его общения с окружающими, - и что с ними делать: как перестать “играть” и личностно вырасти, как избежать негативных сценариев и добиться желаемого. Прочтение помогает чуть больше разобраться в себе и окружающих, понять, почему с тем или иным человек мы себя ведем именно так, а не иначе.",
    "image_urls": [],
    "needs_subscription": false,
    "title": "Эрик Бёрн «Игры, в которые играют люди. Люди, которые играют в игры»."
  },
  {
    "author": "Саша",
    "content": "Из книги можно узнать о том, как нарушения в работе мозга и нервной системы довольно непредсказуемо и удивительно влияют на работу психики - на память, восприятие, мышление. Оливер Сакс разбирает конкретные клинические случаи с личной историей пациента: как меняется их жизнь и как они с этим борются. Книга написана простым языком, вы не запутаетесь в терминологии, а с интересом прочитаете конкретные рассказы с научным объяснением.",
    "image_urls": [
      "/images/Books/человек, который принял жену за шляпу.webp"
    ],
    "needs_subscription": false,
    "title": "Оливер Сакс “Человек, который принял жену за шляпу”."
  },
  {
    "author": "Саша",
    "content": "Книга - сборник исследований по социальной психологии. Авторы доступным языком пересказывают актуальные научные статьи и делятся тем, как можно пользоваться этим в жизни и применять достижения науки на практике. Книга дает знания о том, как можно улаживать межнациональные, межгосударственные и внутриполитические конфликты, как бороться с неуспеваемостью школьников и студентов, справляться с экологическими проблемами и даже сделать так, чтобы люди получали больше удовольствия от жизни.",
    "image_urls": [],
    "needs_subscription": true,
    "title": "Т. Гилович, Л. Росс. Наука мудрости. Как обратить себе на пользу важнейшие открытия социальной психологии."
  },
  {
    "author": "Катя",
    "content": "В книге рассматривается особый подход к пониманию счастья. Счастье для автора сродни вдохновению, а состояние, когда человек полностью поглощен интересным делом, в котором максимально реализует свой потенциал, он называет потоком. Автор обнаруживает, что эмоциональный подъем, который испытывают художники, артисты, музыканты, доступен в любом деле. Более того, к нему надо стремиться – и не только в целенаправленной деятельности, но и в отношениях, в дружбе, в любви. На вопрос, как этому научиться, и отвечает книга.",
    "image_urls": [
      "/images/Books/поток.jpeg"
    ],
    "needs_subscription": false,
    "title": "М. Чиксентмихайи «Поток»"
  },
  {
    "author": "Катя",
    "content": "Книга одного из представителей экзистенциального гуманистического подхода в психотерапии - о том, как нащупать свои внутренние импульсы и научиться с ними обращаться, не игнорируя самому и не позволяя их обесценивать другими. Это стенограмма шести сессий из личной практики, где речь идет о том, что значит по-настоящему быть самим собой, слышать свой внутренний голос, уметь управлять собственной жизнью, понимать свою уникальность.",
    "image_urls": [
      "/images/Books/наука быть живым.jpeg"
    ],
    "needs_subscription": true,
    "title": "Дж. Бьюдженталь «Наука быть живым»"
  },
  {
    "author": "Катя",
    "content": "Книга посвящена психологическим аспектам власти, зависимости и обретения личностей независимости. Обсуждается, почему свободна для некоторых людей представляет угрозу, почему они так легко отказываются от своей индивидуальности, а также о том, как им побороть безразличие к себе и собственной судьбе.",
    "image_urls": [
      "/images/Books/бегство от свободы.jpeg"
    ],
    "needs_subscription": false,
    "title": "Э. Фромм «Бегство от свободы»"
  },
  {
    "author": "Катя",
    "content": "В этой работе философ и психоаналитик Э. Фромм задался целью показать, как развивается любовь. Он, как и многие другие психоаналитики, разграничивает симбиотическое слияние и зрелую любовь. В своей книге он рассказывает, как формируется способность любить, как на это влияет отношение родителей. Он отвечает на вопрос, почему любовь - это акт искусства, и как любое искусство, она требует практики.",
    "image_urls": [],
    "needs_subscription": false,
    "title": "Э. Фромм «Искусство любить. Исследование природы любви»"
  },
  {
    "author": "Никто",
    "content": "Книга посвящена исследованию отношений, а именно - того, как проявляются в них наши старые внутренние конфликты, как связаны в них любовь и ненависть, какова роль сексуальности, как сохранить страстную любовь в длительных отношениях, как влияет социальное окружение на отношения любви.",
    "image_urls": [],
    "needs_subscription": false,
    "title": "О. Кернберг «Отношения любви. Норма и патология»"
  },
  {
    "author": "Ксюша",
    "content": "Книга - основа основ для всех, кто хочет разобраться в психоанализе.",
    "image_urls": [
      "/images/Books/введение в психоанализ.webp"
    ],
    "needs_subscription": false,
    "title": "\"Введение в психоанализ\" Фрейд"
  },
  {
    "author": "Ксюша",
    "content": "В основе сюжета - история реального человека с диссоциативным расстройством личности. Книга захватывает с первой страницы, а после прочтения заставляет задуматься над тем, что же такое \"человек\".",
    "image_urls": [
      "/images/Books/таинственная история билли миллигана.jpeg"
    ],
    "needs_subscription": false,
    "title": "\"Таинственная история Билли Миллигана\" Киз"
  },
  {
    "author": "Ксюша",
    "content": "Книга о нейроотличных людях, становлении личности и о том, как важно всегда оставаться человеком.",
    "image_urls": [
      "/images/Books/цветы для элджернона.jpeg"
    ],
    "needs_subscription": false,
    "title": "\"Цветы для элджернона\" Киз"
  },
  {
    "author": "Арина",
    "content": "Книга учит доносить свои мысли и чувства не прибегая к болезненным манипуляциям. Прочитав эту книгу вы можете научиться находить контакт даже с самыми конфликтными людьми. Принципы ненасильственного общения применимы не только в коммуникации с другими людьми, но и с самим собой.",
    "image_urls": [
      "/images/Books/ненасильственное общение.jpeg"
    ],
    "needs_subscription": false,
    "title": "Ненасильственное общение. Розенберг"
  },
  {
    "author": "Арина",
    "content": "Эта книга является отличным введением в психологию. Она написана в формате диалога первокурсника и аспиранта, поэтому читается легко, даже когда обсуждаются стоицизм или филогенез.",
    "image_urls": [
      "/images/Books/13 диалогов о психологии.jpeg"
    ],
    "needs_subscription": false,
    "title": "13 диалогов о психологии. Соколова"
  },
  {
    "author": "Никто",
    "content": "Научно-популярная книга нейроэндокринолога и приматолога, профессора биологии, неврологии и нейрохирургии Роберта Морриса Сапольски. Эта работа описывает, как различные биологические процессы влияют на поведение человека и вида в промежутках от секунд до тысячелетий.",
    "image_urls": [
      "/images/Books/биология добра и зла.jpeg"
    ],
    "needs_subscription": false,
    "title": "Биология добра и зла. Сапольски"
  },
  {
    "author": "Никто",
    "content": "Несмотря на то, что название может показаться насмешкой в нынешних реалиях, автор обходит наши когнитивные искажения и использует в качестве аргументов научные и исторические данные, а не эмоциональные заголовки. Очень обнадеживающе.",
    "image_urls": [
      "/images/Books/лучшее в нас.jpeg"
    ],
    "needs_subscription": true,
    "title": "Лучшее в нас. Почему насилия в мире стало меньше. Пинкер"
  },
  {
    "author": "Никто",
    "content": "Знаковая книга для тех, кто хочет справиться с травмой. Психическая травма бьет не только по жертве, но и тому, кто рядом. Как распознать ее у себя и близкого человека и чем поможет современная психотерапия?.",
    "image_urls": [
      "/images/Books/тело помнит все.webp"
    ],
    "needs_subscription": false,
    "title": "Тело помнит все. Какую роль психологическая травма играет в жизни человека и какие техники помогают ее преодолеть.  Бессел ван дер Колк"
  },
  {
    "author": "Теодора",
