=== Cortan122/psybot/schemas/state.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "patternProperties": {
    "^message[0-9]+$": {
      "type": "string"
    }
  },
  "properties": {
    "buttons": {
      "oneOf": [
        {
          "items": {
            "items": {
              "anyOf": [
                {
                  "pattern": "^([а-яёА-ЯЁ ]+)|(PLACEHOLDER)$"
                },
                {
                  "format": "uri"
                }
              ],
              "type": "string"
            },
            "type": "array"
          },
          "type": "array"
        },
        {
          "type": "null"
        }
      ]
    },
    "inline_buttons": {
      "type": "boolean"
    },
    "message": {
      "type": "string"
    },
    "one_time_keyboard": {
      "type": "boolean"
    },
    "transitions": {
      "additionalProperties": false,
      "patternProperties": {
        "^([а-яёА-ЯЁ ]+)|(PLACEHOLDER)$": {
          "pattern": "^[A-Z][a-zA-Z]+$",
          "type": "string"
        }
      },
      "properties": {
        "/start": {
          "const": "Start"
        }
      },
      "type": "object"
    }
  },
  "required": [
    "buttons",
    "message",
    "transitions"
  ],
  "type": "object"
}

=== Cortan122/psybot/data/states/AppDownload.json
{
  "buttons": [
    [
      "https://psychological-essence.github.io/PsychologicalEssence.apk"
    ],
    [
      "Назад"
    ]
  ],
  "inline_buttons": true,
  "message": "У нас есть андроид приложение, но его пока нет в Google Play. Поэтому его можно скачать только по ссылке. Там надо будет разрешить установку из сторонних источников, но это не сложно. Я в тебя верю)",
  "transitions": {
    "/start": "Start",
    "Назад": "Start"
  }
}

=== Cortan122/psybot/data/states/QuizCategory.json
{
  "buttons": [
    [
      "Предыдущая страница",
      "Случайный тест",
      "Следующая страница"
    ],
    [
      "В начало"
    ]
  ],
  "message": "Нажмите случайный выбор или введите номер теста",
  "one_time_keyboard": false,
  "transitions": {
    "/start": "Start",
    "В начало": "Start",
    "Предыдущая страница": "THIS",
    "Следующая страница": "THIS",
    "Случайный тест": "THIS"
  }
}

=== Cortan122/psybot/data/states/ArticleCategory.json
{
  "buttons": [
    [
      "Предыдущая страница",
      "Случайная статья",
      "Следующая страница"
    ],
    [
      "В начало"
    ]
  ],
  "message": "Вот список статей в категории «{{CATEGORY}}»",
  "one_time_keyboard": false,
  "transitions": {
    "/start": "Start",
    "В начало": "Start",
    "Предыдущая страница": "THIS",
    "Следующая страница": "THIS",
    "Случайная статья": "THIS"
  }
}

=== Cortan122/psybot/data/states/Quiz.json
{
  "buttons": [
    [
      "PLACEHOLDER"
    ],
    [
      "Предыдущий вопрос",
      "Назад",
      "Завершить тест"
    ]
  ],
  "inline_buttons": true,
  "message": "Вопрос №{{INDEX}} (из {{TOTAL}}) теста «{{NAME}}»",
  "transitions": {
    "/start": "Start",
    "PLACEHOLDER": "NotImplemented",
    "Назад": "THIS"
  }
}

=== Cortan122/psybot/data/states/TechniqueCategory.json
{
  "buttons": [
    [
      "Предыдущая страница",
      "Случайная техника",
      "Следующая страница"
    ],
    [
      "В начало"
    ]
  ],
  "message": "Нажмите случайный выбор или введите номер техники",
  "one_time_keyboard": false,
  "transitions": {
    "/start": "Start",
    "В начало": "Start",
    "Предыдущая страница": "THIS",
    "Следующая страница": "THIS",
    "Случайная техника": "THIS"
  }
}

=== Cortan122/psybot/data/states/Recommendations.json
{
  "buttons": [
    [
      "Книги",
      "Фильмы",
      "Сериалы"
    ],
    [
      "Назад"
    ]
  ],
  "inline_buttons": true,
  "message": "Не знаете что еще прочесть или посмотреть по психологии? Выбирайте категорию и мы поможем вам не заскучать в свободный вечер",
  "transitions": {
    "/start": "Start",
    "Книги": "BookRecommendations",
    "Назад": "Start",
    "Сериалы": "SeriesRecommendations",
    "Фильмы": "FilmRecommendations"
  }
}

=== Cortan122/psybot/data/states/Techniques.json
{
  "buttons": [
    [
      "PLACEHOLDER"
    ],
    [
      "Назад"
    ]
  ],
  "inline_buttons": true,
  "message": "Раздел содержит различные техники улучшения собственной осознанной жизни. Собранные нами техники помогут вам в этом.",
  "transitions": {
    "/start": "Start",
    "PLACEHOLDER": "NotImplemented",
    "Назад": "Start"
  }
}
